name: Work between jobs

on: workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Ubuntu Version
        run: cat /etc/os-release

      - name: Write a message
        run: echo "Hello world, im running my second workflow!" > message.txt

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: File not available in this job right now
        run: ls -lha

      - name: Trying access message file
        run: cat message.txt
