name: Work between jobs

on: workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Ubuntu Version
        run: cat /etc/os-release

      - name: Write a message
        run: echo "Creating message.txt in job_1" > ${{ github.workspace }}/message.txt

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: strigus-upload

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ${{ github.workspace }}/message.txt

          if-no-files-found: error

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: File not available in this job right now
        run: ls -lha

      - uses: actions/download-artifact@v5
        with:
          name: strigus-upload
          path: strigus

      - name: File availabe in strigus folder
        run: ls -lha && ls ${{ github.workspace }}/strigus

      - name: Trying access message file
        run: mv strigus/message.txt . && rm -rf ./strigus

      - name: File availabe in root
        run: ls -lha

      - name: access message file after artifact download
        run: cat message.txt
